version: "3.8"
services: 
  api:
    image: ase-api
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/ase_db
      spring.datasource.username: postgres
      spring.datasource.password: password
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ase_db
    ports: 
      - 5432:5432
